/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.cameraData;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Ocr_Camera;

/**
 *
 * @author marco.junior
 */
public class Form_Innova extends javax.swing.JFrame {
    
    private Ocr_Camera ocr;
    private cameraData DAO;
    public Form_Innova() throws Exception {
        initComponents();
            jtIdLane.setEnabled(false);
            jtIdEquipamentoSpace.setEnabled(false);
            jtIp.setEnabled(false);
            jtDiretorioArmazenaImagem.setEnabled(false);
            jtUrlArmazenaImagem.setEnabled(false);
            jtCameraPorta.setEnabled(false);
            jtIdTipoCamera.setEnabled(false);
        DAO = new cameraData();        
    }      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jtSenhaFtp = new javax.swing.JTextField();
        jtDiretorioFtp = new javax.swing.JTextField();
        jtDirecao = new javax.swing.JTextField();
        jtDiretorioArmazenaImagem = new javax.swing.JTextField();
        jtUrlArmazenaImagem = new javax.swing.JTextField();
        jtMac = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtIdLane = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtUsuarioFtp = new javax.swing.JTextField();
        jtIdEquipamentoSpace = new javax.swing.JFormattedTextField();
        jtIp = new javax.swing.JFormattedTextField();
        jtCameraPorta = new javax.swing.JFormattedTextField();
        jNovo = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jtIdTipoCamera = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CAMERA INNOVA");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtSenhaFtp.setEditable(false);
        jtSenhaFtp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtSenhaFtp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtSenhaFtp.setText("1A464");
        jtSenhaFtp.setToolTipText("Senha do FTP");
        jtSenhaFtp.setEnabled(false);
        jPanel1.add(jtSenhaFtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 61, -1));

        jtDiretorioFtp.setEditable(false);
        jtDiretorioFtp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtDiretorioFtp.setText("\\Log");
        jtDiretorioFtp.setToolTipText("Logs da aplicação");
        jtDiretorioFtp.setEnabled(false);
        jPanel1.add(jtDiretorioFtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 39, -1));

        jtDirecao.setEditable(false);
        jtDirecao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtDirecao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtDirecao.setToolTipText("");
        jtDirecao.setEnabled(false);
        jPanel1.add(jtDirecao, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 19, -1));

        jtDiretorioArmazenaImagem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jtDiretorioArmazenaImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 243, -1));

        jtUrlArmazenaImagem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jtUrlArmazenaImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 243, -1));

        jtMac.setEditable(false);
        jtMac.setToolTipText("NÃO UTILIZADO");
        jtMac.setEnabled(false);
        jPanel1.add(jtMac, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 60, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("CONFIGURAÇÃO CAMERAS INNOVA");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("ID CAMERAS");
        jLabel1.setToolTipText("ID configurado para cada par de cameras no SIRAM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        try {
            jtIdLane.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtIdLane.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtIdLane.setToolTipText("ID configurado para cada par de cameras no SIRAM");
        jtIdLane.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtIdLane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIdLaneActionPerformed(evt);
            }
        });
        jPanel1.add(jtIdLane, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 60, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("ID DO EQUIPAMENTO");
        jLabel2.setToolTipText("ID do equipamento Nepos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("IP SERVIDOR");
        jLabel3.setToolTipText("IP onde a aplicação SIRAM está instalado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("USUARIO FTP");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("SENHA FTP");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("DIRETORIO FTP");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("DIREÇÃO");
        jLabel7.setToolTipText("NÃO UTILIZADO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("DIRETORIO_ARMAZENA_IMAGEM");
        jLabel8.setToolTipText("Diretório onde será armazenada as imagens");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("URL_ARMAZENA_IMAGEM");
        jLabel9.setToolTipText("URL onde serão publicadas as imagens");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("MODELO DA CAMERA");
        jLabel10.setToolTipText("Tipo de Camera default como 3 ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("CAMERA_PORTA");
        jLabel11.setToolTipText("Porta da Camera que foi configurada no SirawTwinPlate");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("MAC");
        jLabel12.setToolTipText("NÃO UTILIZADO");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jtUsuarioFtp.setEditable(false);
        jtUsuarioFtp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtUsuarioFtp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtUsuarioFtp.setText("admin");
        jtUsuarioFtp.setEnabled(false);
        jtUsuarioFtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtUsuarioFtpActionPerformed(evt);
            }
        });
        jPanel1.add(jtUsuarioFtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 61, -1));

        try {
            jtIdEquipamentoSpace.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtIdEquipamentoSpace.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtIdEquipamentoSpace.setToolTipText("ID do equipamento Nepos");
        jtIdEquipamentoSpace.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jtIdEquipamentoSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 60, -1));

        try {
            jtIp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtIp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtIp.setToolTipText("");
        jtIp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jtIp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 120, -1));

        try {
            jtCameraPorta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtCameraPorta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtCameraPorta.setToolTipText("Porta da Camera que foi configurada no SirawTwinPlate");
        jtCameraPorta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jtCameraPorta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 63, -1));

        jNovo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jNovo.setText("NOVO");
        jNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNovoActionPerformed(evt);
            }
        });
        jPanel1.add(jNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 111, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("CANCELAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("INCLUIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 100, -1));

        jtIdTipoCamera.setEditable(true);
        jtIdTipoCamera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", " " }));
        jtIdTipoCamera.setAutoscrolls(true);
        jPanel1.add(jtIdTipoCamera, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 60, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 610, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 610, 10));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel15.setText("CONFIGURAÇÃO DA CAMERA");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel16.setText("CONFIGURAÇÕES FTP");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel17.setText("CONFIGURAÇÃO DIRETÓRIO");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 610, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 610, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 610, 10));

        jLabel14.setText("Obs: As configurações FTP padronizadas");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 210, 20));

        jMenu1.setText("Arquivo");

        jMenuItem3.setText("Relatório");
        jMenu1.add(jMenuItem3);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cameras");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Cameras Cadastradas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(626, 538));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtUsuarioFtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtUsuarioFtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtUsuarioFtpActionPerformed

    private void jtIdLaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIdLaneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIdLaneActionPerformed

    private void jNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNovoActionPerformed
            jtIdLane.setEnabled(true);
            jtIdEquipamentoSpace.setEnabled(true);
            jtIp.setEnabled(true);
            jtDiretorioArmazenaImagem.setEnabled(true);
            jtUrlArmazenaImagem.setEnabled(true);
            jtCameraPorta.setEnabled(true);
            jtIdTipoCamera.setEnabled(true);
    }//GEN-LAST:event_jNovoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            jtIdLane.setText("");
            jtIdEquipamentoSpace.setText("");
            jtIp.setText("");
            jtDiretorioArmazenaImagem.setText("");
            jtUrlArmazenaImagem.setText("");
            jtCameraPorta.setText("");      
            jtIdLane.setEnabled(false);
            jtIdEquipamentoSpace.setEnabled(false);
            jtIp.setEnabled(false);
            jtDiretorioArmazenaImagem.setEnabled(false);
            jtUrlArmazenaImagem.setEnabled(false);
            jtCameraPorta.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
        
        try {
            preencherObjeto();
            DAO.inserir(ocr);
            JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso ");
        } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null,"ERRO : " +ex.getMessage());
        }
        
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        try {
            Form_Cadastro camera = new Form_Cadastro();
            camera.setVisible(true);
        } catch (Exception ex) {
            System.out.println("Erro  " +ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(null,"Aplicativo encerrado");
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Innova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Innova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Innova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Innova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Form_Innova().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Form_Innova.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JButton jNovo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JFormattedTextField jtCameraPorta;
    private javax.swing.JTextField jtDirecao;
    private javax.swing.JTextField jtDiretorioArmazenaImagem;
    private javax.swing.JTextField jtDiretorioFtp;
    private javax.swing.JFormattedTextField jtIdEquipamentoSpace;
    private javax.swing.JFormattedTextField jtIdLane;
    private javax.swing.JComboBox<String> jtIdTipoCamera;
    private javax.swing.JFormattedTextField jtIp;
    private javax.swing.JTextField jtMac;
    private javax.swing.JTextField jtSenhaFtp;
    private javax.swing.JTextField jtUrlArmazenaImagem;
    private javax.swing.JTextField jtUsuarioFtp;
    // End of variables declaration//GEN-END:variables

public boolean preencherObjeto()
{
    ocr = new Ocr_Camera();
    ocr.setId_lane(jtIdLane.getText());
    ocr.setId_equipamento_space(jtIdEquipamentoSpace.getText());
    ocr.setIp(jtIp.getText());
    ocr.setUsuario_ftp(jtUsuarioFtp.getText());
    ocr.setSenha_ftp(jtSenhaFtp.getText());
    ocr.setDiretorio_ftp(jtDiretorioFtp.getText());
    ocr.setDirecao(jtDirecao.getText());
    ocr.setDiretorio_armazena_imagem(jtDiretorioArmazenaImagem.getText());
    ocr.setUrl_armazena_imagem(jtUrlArmazenaImagem.getText());
    ocr.setId_tipo_camera((String) jtIdTipoCamera.getSelectedItem());
    ocr.setCamera_porta(jtCameraPorta.getText());
    ocr.setMac(jtMac.getText());
    
    return true;
}
  

}
